"""add BlacklistedToken model

Revision ID: 079d26d45cc9
Revises: eb6c2faa0708
Create Date: 2020-02-29 00:49:46.911134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "079d26d45cc9"
down_revision = "eb6c2faa0708"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
